language: python

python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

before_script: import os

# command to run tests
script: python unit_tests/__init__.py